[versions]
kotter = "1.4.0-SNAPSHOT"
#------------------------
atomicfu = "0.33.0"
dokka = "2.2.0"
jline = "4.3.1"
jsvg = "2.1.0"
kotlinx-coroutines = "1.11.0"
kotlin = "2.2.21"
kover = "0.9.8"
truthish = "1.0.3"
vanniktech-publish = "0.37.0"

[libraries]
jcip-annotations = { module = "net.jcip:jcip-annotations", version = "1.0" }
jetbrains-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
jline-terminal-core = { module = "org.jline:jline-terminal", version.ref = "jline" }
jline-terminal-jni = { module = "org.jline:jline-terminal-jni", version.ref = "jline" }
jline-terminal-ffm = { module = "org.jline:jline-terminal-ffm", version.ref = "jline" }
jsvg = { module = "com.github.weisj:jsvg", version.ref = "jsvg" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-multiplatform-plugin = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
truthish = { module = "com.varabyte.truthish:truthish", version.ref = "truthish" }
vanniktech-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }

[plugins]
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-publish" }

[bundles]
# jline will pick the appropriate one
# ffm for JDK22+, JNI for older. A clunky system fallback is available if all providers fail.
jline-terminal-providers = ["jline-terminal-jni", "jline-terminal-ffm"]
